### ISSUE TITLE
您好，请问GB2312点阵bin文件该如何读取？

### ISSUE THREAD

**Issue by MasterYuan418** [Dreagonmon/micropython-toolkit#1]
使用GB2312的点阵文件，但是不太明白该如何去读取字模并将其显示到屏幕上，使用TS4软件也无法正常读取

**Comment by Dreagonmon** [comment]
你使用的是哪个文件？用哪个脚本生成的？

**Comment by MasterYuan418** [comment]
使用的是text_utils/codecs/codecs_utf8_gb2312.bin

**Comment by Dreagonmon** [comment]
使用示例参考codecs_utf8_gb2312.test.py
其中codecs_utf8_gb2312.py模块的依赖coding模块在text_utils/coding/下面

**Comment by MasterYuan418** [comment]
您好，很感谢您的解答！
但是，我的意思是使用点阵字库将中文汉字显示到屏幕上（也就是screen_utils/utils/ubmfont.py所做的），但我无法使用UTF-8，必须使用GB2312，但您的`ubmfont`貌似只支持`UTF-8`的字库

**Comment by Dreagonmon** [comment]
这里是utf8编码转换成gb2312的代码

ubmfont直接使用utf8编码，不需要转换。

转成gb2312之后，就按照正常的gb2312字体绘制嘛

**Comment by MasterYuan418** [comment]
是的，关键就是在绘制GB2312字体这里，我找不到类似的教程，把基于UTF8的一套改了一下发现不能用😕

**Comment by Dreagonmon** [comment]
这个你需要自己找找HZK16字体的相关绘制方法，同时有必要了解一下gb2312编码。我这个repo里面没有相关的代码。

**Comment by MasterYuan418** [comment]
好的，感谢您的回答
